// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type ReportedFile struct {
	WatcherPath string
	FilePath    string
	ReportedAt  string
}

type Watcher struct {
	Path        string
	FirstSeenAt string
}
