// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const addReportedFile = `-- name: AddReportedFile :exec
INSERT INTO reported_files (watcher_path, file_path) VALUES (?, ?)
ON CONFLICT (watcher_path, file_path) DO NOTHING
`

type AddReportedFileParams struct {
	WatcherPath string
	FilePath    string
}

func (q *Queries) AddReportedFile(ctx context.Context, arg AddReportedFileParams) error {
	_, err := q.db.ExecContext(ctx, addReportedFile, arg.WatcherPath, arg.FilePath)
	return err
}

const listReportedFiles = `-- name: ListReportedFiles :many
SELECT file_path FROM reported_files WHERE watcher_path = ?
`

func (q *Queries) ListReportedFiles(ctx context.Context, watcherPath string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listReportedFiles, watcherPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerWatcher = `-- name: RegisterWatcher :execrows
INSERT INTO watchers (path) VALUES (?) ON CONFLICT (path) DO NOTHING
`

func (q *Queries) RegisterWatcher(ctx context.Context, path string) (int64, error) {
	result, err := q.db.ExecContext(ctx, registerWatcher, path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeReportedFile = `-- name: RemoveReportedFile :exec
DELETE FROM reported_files WHERE watcher_path = ? AND file_path = ?
`

type RemoveReportedFileParams struct {
	WatcherPath string
	FilePath    string
}

func (q *Queries) RemoveReportedFile(ctx context.Context, arg RemoveReportedFileParams) error {
	_, err := q.db.ExecContext(ctx, removeReportedFile, arg.WatcherPath, arg.FilePath)
	return err
}
